### ISSUE TITLE
Get an Apple developer account

### ISSUE THREAD

**Issue by asktheo** [birdlifedk/DOFI#9]
for DOF - Birdlife DK

**Comment by asktheo** [comment]
Hej, kan denne lukkes ?

**Comment by DOFandersolsen** [comment]
Vi er stadig ved at få oprettet en konto, jeg fik svar i dag hvor vi skulle ændre navnet på AppleID-kontoen, hvilket jeg har gjort, og så er vi sat til godkendelse igen.

**Comment by asktheo** [comment]
Så er den klaret. Indtil videre er 2 mailadresser under nodes.dk tilmeldt som admins
